### ISSUE TITLE
Triplet feel during playback

### ISSUE THREAD

**Issue by cheap-glitch** [CoderLine/alphaTab#246] opened 2019-03-09 14:34 UTC
# Description 
While it's possible to indicate a triplet feel in alphaTex, it only generates a visual indication. It would be great if the triplet feel was reflected in the actual playback of the score.

# Possible Solutions

# Current Workarounds 
Some kind of parser that would apply the triplet feel directly to the alphaTex code by altering the durations of the notes accordingly, before creating the tab.

**Comment by Danielku15** [comment] 2019-03-09 18:38
Closing as duplicate of #107

**Closed by Danielku15** 2019-03-09 18:38 UTC
