### ISSUE TITLE
Can i build the source on Mac?

### ISSUE THREAD

**Issue by zhouhuakang** [CoderLine/alphaTab#158] opened 2017-08-09 12:55 UTC
# Your environment
Mac:
* Version used: (master branch)
* Platform used: JavaScript or C#
* Rendering engine used: SVG (default), HTML5 or GDI
* Browser Name and Version: 
* Operating System and version (desktop or mobile):
* Link to your project:

# Expected Results
          I want to try contribute the source code,but i do not have a computer with the windows os,so i want to develop the alphaTab on mac,Can I ？
Explain here what is your expected behavior of alphaTab. 

# Observed Results
       If it can ,please show me the simple steps!thanks!
Explain here how alphaTab is behaving currently. 

# Steps to Reproduce (for bugs)

Explain here the exact steps how to reproduce the problem. Try to provide a
running sample showing the issue. If you have problem with a dedicated input file, 
please provide a download link or attach it to the issue. 
 
1. 
2. 
3.  

# Possible Solution 
If you already know a solution to the problem please provide it here.

**Comment by Danielku15** [comment] 2017-08-10 07:47
Duplicate of #80 
Yes. You can download MonoDevelop and compile using the special "MonoDebug" and "MonoRelease" build configurations.

**Closed by Danielku15** 2017-08-10 07:47 UTC
