### ISSUE TITLE
Nested repeat

### ISSUE THREAD

**Issue by hd-i** [CoderLine/alphaTab#658] opened 2021-09-08 12:24 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Currently ,it cannot handle this behavior and after the finished first time of main repeat , for play second time of main repeat , repeat started from the end of the inside repeat.

### Expected Behavior

for second time , It should playing from start of main repeat that is opened.

### Steps To Reproduce

.

### Found in Version

1.3-alpha

### Platform

Web

### Environment

```markdown
- **OS**: Windows 10
- **Browser**: Chrome - Firefox
- **.net Version**:
```

**Comment by Danielku15** [comment] 2021-09-26 13:35
Please provide provide proper steps to reproduce otherwise I will not be able to help here. Try to provide a minimal working example of your issue.

**Comment by Danielku15** [comment] 2021-11-04 16:47
@hd-i Any update on your problems? Otherwise I will close this issue.

**Comment by Danielku15** [comment] 2021-11-28 16:15
Closed due to inactivity

**Closed by Danielku15** 2021-11-28 16:15 UTC
Labels: :spider: type-bug, area-player, :speech_balloon: state-needs-discussion, platform-javascript
