### ISSUE TITLE
Play needle lags behind bug

### ISSUE THREAD

**Issue by BorninDusk** [CoderLine/alphaTab#255] opened 2019-06-02 07:35 UTC
# Your environment

* Version used: (master branch)
* Platform used: JavaScript.
* Rendering engine used: SVG (default).
* Browser Name and Version: Chrome latest
* Operating System and version (desktop or mobile): Linux, Ubuntu 18.04
* Link to your project:

# Expected Results

Smooth transitions between tracks with the play needle on top of the currently played note.

# Observed Results

The play needle lags behind after pressing play, pausing then switching track and then pressing play again

# Steps to Reproduce (for bugs)

1. Play any track for any amount of time.
2. Pause the currently played track.
3. Switch to a different track and press the play button
4. Observe that the play needle is behind the currently played note. 

# Possible Solution 

This can be fixed by stopping and replaying the tab but this would be tedious if you were far into  the tab. Also seeking to a different part seems to resolve it.
Here's a link to a video showing the bug https://drive.google.com/file/d/1L0V87c5VxnDXnTru-7M9eklcIUBcL9sK/view?usp=sharing 
On some faster songs it is much worse.

**Comment by Danielku15** [comment] 2019-07-04 12:37
This is really a nasty issue. Actually it is not caused by the switching if the track, but can already be seen when doing a simple pause resume. I fear there is some latency issue within the player which causes the wrong time position to be reported to the cursor. The same issue exists on Windows and on all browsers I tested.

My steps were: 

1. Open https://docs.alphatab.net/develop/assets/files/player/player.html
2. Press play and wait a bit
3. Pause and wait a bit
4. Press play again -> Issue appears.

**Comment by Danielku15** [comment] 2019-07-28 15:17
I was able to identify the issue and as expected it was due to the buffered audio part in the Web Audio API. On pause some samples were discarded but they were already considered as played. This way the cursor was ahead the playback. 

I first made a fix where I was able to calculate the latency and the cursor behaved correct. But then I redecided on the general cursor behavior. 

Now with the fix, the full beat where the cursor is, will be replayed. This means, the cursor now really represents the start position. 

Technically spoken: On pause I seek back to the beat just like the cursor does,. 

Please have a look if it it fits now also your expectations

**Comment by BorninDusk** [comment] 2019-07-28 19:48
yes this is exactly what should be expected

**Comment by Danielku15** [comment] 2019-07-29 10:58
Great to hear. Closing this issue then.

**Closed by Danielku15** 2019-07-29 10:58 UTC
Labels: :spider:  bug, accepted, alphaSynth, needs-investigation, platform-javascript
