### ISSUE TITLE
How are you going to support iOS version?

### ISSUE THREAD

**Issue by zhouhao27** [CoderLine/alphaTab#68] opened 2015-11-16 04:48 UTC
I'm wondering how you're going to support iOS ?  By compile it to c++ library? If I'd like to help, where should I start? Thanks.

**Comment by zhouhao27** [comment] 2015-11-17 07:52
I'm also thinking if it's possible to transfer the gtp,gpx parser code into swift so that at least the parser will be possibly used by iOS.

**Comment by Danielku15** [comment] 2016-09-01 18:29
Duplicate of #75

**Closed by Danielku15** 2016-09-01 18:29 UTC

**Comment by zhouhao27** [comment] 2016-09-03 03:02
Actually I'm thinking it's not an issue to support the parser based on the current code. But rendering the music score is definitely different. Probably need to find out a library doing this.

**Comment by Danielku15** [comment] 2016-09-03 10:44
In the end the topic will remain the same: We need a toolkit that translates the C# code base to Swift/C++ and Java. So far I could not find any mature project which does that. The code itself is designed to be compiled for various platforms. The core of alphaTab uses only very simple types. Platform specific types come in through an abstraction layer.
