### ISSUE TITLE
Unclear docs for initializing alphaSynth (paths need to be rooted)

### ISSUE THREAD

**Issue by ShredDead** [CoderLine/alphaTab#83] opened 2016-04-09 19:03 UTC
![alphatab](https://cloud.githubusercontent.com/assets/18369457/14405778/3fa5585e-fe5b-11e5-8b53-8423a66f2b7e.jpg)

I have tried everything, including disabling NoScript, but I cannot get the soundfont to load in the player.html nor will Canon.gp5 render within the features.html file. I have the alphaTab-master folder loaded into my root testing server and on my live server, but nothing. But...it works on yours. What is the problem that I'm having?

Thanks.

**Comment by Danielku15** [comment] 2016-04-09 19:34
Can you check if there is any error written in the developer tools of the browser (F12). What WebServer are you running? If you're testing with IIS it might be that you need to add the .sf2 extension to the web.config so it get's provided to the clients: 

    <?xml version="1.0" encoding="utf-8"?>
    <configuration>
        <system.webServer>
            <staticContent>
            <mimeMap fileExtension=".gp3" mimeType="application/gp3" />
            <mimeMap fileExtension=".gp4" mimeType="application/gp4" />
            <mimeMap fileExtension=".gp5" mimeType="application/gp5" />
            <mimeMap fileExtension=".gpx" mimeType="application/gp6" />
            <mimeMap fileExtension=".sf2" mimeType="application/soundfont2" />
            <mimeMap fileExtension=".woff" mimeType="application/woff" />
            </staticContent>
      </system.webServer>
    </configuration>

Also check the "Network Analysis" tab in the developer tools when opening the page. You should see that the browser requests the default.sf2 and likely you get an error response.

**Comment by ShredDead** [comment] 2016-04-09 19:47
I'm using Apache on my live and testing server. Here is a screenshot of Network within Firefox. But the file is there.

![alphatab2](https://cloud.githubusercontent.com/assets/18369457/14406001/e45900f2-fe61-11e5-8201-826ddd7c16ab.jpg)

**Comment by ShredDead** [comment] 2016-04-09 20:02
Here's another screenshot.

![alphatab3](https://cloud.githubusercontent.com/assets/18369457/14406129/f9eafb94-fe63-11e5-8faa-8c1648aa97c1.jpg)

**Comment by ShredDead** [comment] 2016-04-09 21:42
Okay! I figured the problem out. I cannot have the folder "alphaTab-master" within the root. All the files within that folder must be uploaded to the root directory! This should be corrected. How can this be resolved?

Also, there is an error in the index.html file of /Samples/JavaScript/
It is asking for featuress.html which needs to be corrected to features.html

**Comment by Danielku15** [comment] 2016-04-09 22:51
Adjusting the paths in the player.html accordingly should do the job. Change it like this: 

    var as = at.alphaTab('playerInit', {
        asRoot: '/alphatab-master/Samples/JavaScript/lib/alphaSynth/',
        swfObjectRoot: '/alphatab-master/Samples/JavaScript/lib/alphaSynth/'
    }); // init alphaSynth

Since web workers run in a separate context within the browser, it's not easily possible to use relative paths to load the required scripts. I will need to write some docs to make it more clear how to setup the samples. Thanks for this finding. 

Regardin the broken scrolling I added another issue: #84

**Comment by ShredDead** [comment] 2016-04-09 23:15
Thank you. I did that earlier but maybe my browser needed to have the cache cleared. One more question please. How can I select which track to be rendered? I have seven tracks within a file and for some reason the one that is being displayed is the fourth one which is the Bass.

**Comment by Danielku15** [comment] 2016-04-10 09:01
`data-tracks` is 0 indexed (like an array) and Guitar Pro starts with 1 of course for end-user display. This behavior is by design.

**Comment by Danielku15** [comment] 2017-08-01 18:32
Relative paths should not be a problem anymore, they are supported since quite a while. Initialization also became easier with the use of data attributes. 
Closing this issue.

**Closed by Danielku15** 2017-08-01 18:32 UTC
Labels: Accepted, Improvement
