### ISSUE TITLE
Horizontal Display results in no Title/subtitle etc.

### ISSUE THREAD

**Issue by dgriessler** [CoderLine/alphaTab#333] opened 2020-02-14 17:40 UTC
# Description 

Choosing horizontal layout results in no metadata being displayed above the music.  I would like to be able to tell enable the metadata such as title/subtitle etc. when in horizontal layout.

# Possible Solutions

I'm not fully sure how to fix this issue other than to just keep the metadata between vertical and horizontal display.

# Current Workarounds 

I can extract and display the title/subtitle etc. by parsing the AlphaTex and displaying in a separate div but it would be nice if it was built in.

**Comment by Danielku15** [comment] 2020-02-15 17:41
As of today this is the expected behavior and not a bug. The song metadata display is a feature of the "page" layout only as they are considered as "page headers and footers" for printing. This is aligned with the behavior of GuitarPro which also only shows the metadata for "page" layouts. 

It might make sense as a new feature to add song meta support for horizontal layouts. I'd need to check how to align the elements best in this case. Could you convert the issue to the feature request template to be sure the feature will ship what you need?

**Comment by dgriessler** [comment] 2020-02-15 18:30
Updated to feature request.

**Comment by Danielku15** [comment] 2020-07-27 15:57
I investigated some approaches on how to show the song metadata best in horizontal layout but somehow none really worked out well. It rather introduces various issues on the layouting. 

But as a replacement I decided to write a small guide on how you can easily build an own UI for showing the song metadata:

https://www.alphatab.net/docs/guides/song-details

In fact I decided that it would be even better to remove also the display of the metadata on the page layout. But I do not want to introduce already in 1.1 such breaking changes so it will stay in a bit longer until maybe a 2.0 comes along with other breaking changes.

**Comment by dgriessler** [comment] 2020-07-27 16:01
Sounds good though your url is broken ^

**Comment by Danielku15** [comment] 2020-07-27 16:03
That was quick. Publish is still ongoing 😄 

https://github.com/CoderLine/alphaTabWebsite/actions

**Comment by dgriessler** [comment] 2020-07-27 16:10
Alright, cool. Thanks

**Comment by Danielku15** [comment] 2020-07-27 16:11
I'm closing this issue now. Feel free to re-open this or a new one if something is missing 😉

**Closed by Danielku15** 2020-07-27 16:11 UTC
Labels: :bulb: type-feature-request, :speech_balloon: state-needs-discussion, area-rendering, priority-medium
