### ISSUE TITLE
Load MusicXml issues

### ISSUE THREAD

**Issue by LYH8112** [CoderLine/alphaTab#129] opened 2017-03-22 01:20 UTC
Load musicxml file, only the first measure is ok. 
![image](https://cloud.githubusercontent.com/assets/23731747/24177927/9f5043f4-0ee0-11e7-80a4-923928b4d449.png)

**Comment by Danielku15** [comment] 2017-03-22 18:22
Can you please provide the MusicXML file you used for testing? 
MusicXML is really a horrible format in some ways. It's not fully clear from the screenshot what causes this.

**Comment by gburlet** [comment] 2017-03-22 18:37
@Danielku15 maybe we should create a `contributing.md` with a link to `contributing.md` in the `README.md` that provides a template for bug/issue reports to help avoid vague issues like this in the future. This would also avoid "More Info Required" tags in the future.

For example, [this template](https://github.com/TalAter/open-source-templates/blob/master/ISSUE_TEMPLATE.md) is pretty minimal and might work well for our needs. We could also add a field to include any data files that result in bugs.

**Comment by LYH8112** [comment] 2017-03-23 01:21
@Danielku15 Please check the MusicXM
[Uploading 1.txt…]()
L file.

**Comment by Danielku15** [comment] 2017-03-27 18:02
@gburlet Thanks for the reminder. I started a template once but somehow I ran from one thing into the next and never uploaded a proper one. 

@LYH8112: The file was not properly attached to the issue and cannot be downloaded. Please upload it again.

**Comment by LYH8112** [comment] 2017-03-28 02:14
@Danielku15 The file was not uploaded.  If disabled the code, it is ok. please check.
 //for (int v = 0; v < _maxVoices; v++)
 //{
          //    var emptyVoice = new Voice();
          //    bar.AddVoice(emptyVoice);
           //    var emptyBeat = new Beat { IsEmpty = true };
           //    emptyVoice.AddBeat(emptyBeat);
  //}

<?xml version="1.0" encoding='UTF-8' standalone='no' ?>
<!DOCTYPE score-partwise PUBLIC "-//Recordare//DTD MusicXML 3.0 Partwise//EN" "http://www.musicxml.org/dtds/partwise.dtd">
<score-partwise version="3.0">
 <work>
  <work-title />
 </work>
 <identification> 
  <encoding>
   <encoding-date>2016-12-30</encoding-date>
   <encoder>ganw</encoder>
   <software>Sibelius 7.5.0</software>
   <software>Direct export, not from Dolet</software>
   <encoding-description>Sibelius / MusicXML 3.0</encoding-description>
   <supports element="print" type="yes" value="yes" attribute="new-system" />
   <supports element="print" type="yes" value="yes" attribute="new-page" />
   <supports element="accidental" type="yes" />
   <supports element="beam" type="yes" />
   <supports element="stem" type="yes" />
  </encoding>
 </identification>
 <defaults>
  <scaling>
   <millimeters>210</millimeters>
   <tenths>1200</tenths>
  </scaling>
  <page-layout>
   <page-height>1697</page-height>
   <page-width>1200</page-width>
   <page-margins type="both">
    <left-margin>72</left-margin>
    <right-margin>72</right-margin>
    <top-margin>72</top-margin>
    <bottom-margin>72</bottom-margin>
   </page-margins>
  </page-layout>
  <system-layout>
   <system-margins>
    <left-margin>22</left-margin>
    <right-margin>0</right-margin>
   </system-margins>
   <system-distance>92</system-distance>
  </system-layout>
  <appearance>
   <line-width type="stem">0.9375</line-width>
   <line-width type="beam">5</line-width>
   <line-width type="staff">0.9375</line-width>
   <line-width type="light barline">1.5625</line-width>
   <line-width type="heavy barline">5</line-width>
   <line-width type="leger">1.5625</line-width>
   <line-width type="ending">1.5625</line-width>
   <line-width type="wedge">1.25</line-width>
   <line-width type="enclosure">0.9375</line-width>
   <line-width type="tuplet bracket">1.25</line-width>
   <line-width type="bracket">5</line-width>
   <line-width type="dashes">1.5625</line-width>
   <line-width type="extend">0.9375</line-width>
   <line-width type="octave shift">1.5625</line-width>
   <line-width type="pedal">1.5625</line-width>
   <line-width type="slur middle">1.5625</line-width>
   <line-width type="slur tip">0.625</line-width>
   <line-width type="tie middle">1.5625</line-width>
   <line-width type="tie tip">0.625</line-width>
   <note-size type="cue">75</note-size>
   <note-size type="grace">60</note-size>
  </appearance>
  <music-font font-family="Opus Std" font-size="19.8425" />
  <lyric-font font-family="SimHei" font-size="11.4715" />
  <lyric-language xml:lang="zh" />
 </defaults>
 <part-list>
  <score-part id="P1">
   <part-name> </part-name>
   <part-name-display>
    <display-text> </display-text>
   </part-name-display>
   <part-abbreviation> </part-abbreviation>
   <part-abbreviation-display>
    <display-text> </display-text>
   </part-abbreviation-display>
   <score-instrument id="P1-I1">
    <instrument-name> </instrument-name>
    <virtual-instrument>
     <virtual-library>General MIDI</virtual-library>
     <virtual-name>Bright Piano</virtual-name>
    </virtual-instrument>
   </score-instrument>
  </score-part>
 </part-list>
 <part id="P1">
  
  <measure number="1" width="312">
   <print new-page="yes">
    <system-layout>
     <system-margins>
      <left-margin>22</left-margin>
      <right-margin>0</right-margin>
     </system-margins>
     <top-system-distance>218</top-system-distance>
    </system-layout>
   </print>
   <attributes>
    <divisions>256</divisions>
    <key color="#000000">
     <fifths>1</fifths>
     <mode>major</mode>
    </key>
    <time color="#000000">
     <beats>3</beats>
     <beat-type>4</beat-type>
    </time>
    <staves>1</staves>
    <clef number="1" color="#000000">
     <sign>G</sign>
     <line>2</line>
    </clef>
    <staff-details number="1" print-object="yes" />
   </attributes>
   <direction directive="yes">
    <direction-type>
     <metronome default-y="30" color="#000000" font-family="Opus Text Std" font-style="normal" font-size="11.9365" font-weight="normal">
      <beat-unit>quarter</beat-unit>
      <per-minute>70</per-minute>
     </metronome>
    </direction-type>
    <voice>1</voice>
    <staff>1</staff>
   </direction>
   <note color="#000000" default-x="88" default-y="-55">
    <pitch>
     <step>B</step>
     <octave>4</octave>
    </pitch>
    <duration>512</duration>
    <instrument id="P1-I1" />
    <voice>1</voice>
    <type>half</type>
    <stem>down</stem>
    <staff>1</staff>
   </note>
   <note color="#000000" default-x="198" default-y="12">
    <pitch>
     <step>G</step>
     <octave>4</octave>
    </pitch>
    <duration>85</duration>
    <instrument id="P1-I1" />
    <voice>1</voice>
    <type>eighth</type>
    <time-modification>
     <actual-notes>3</actual-notes>
     <normal-notes>2</normal-notes>
     <normal-type>eighth</normal-type>
    </time-modification>
    <stem>up</stem>
    <staff>1</staff>
    <beam number="1">begin</beam>
    <notations>
     <tuplet type="start" bracket="no" number="1" default-y="-20" placement="above" />
    </notations>
   </note>
   <note color="#000000" default-x="236" default-y="12">
    <pitch>
     <step>B</step>
     <octave>4</octave>
    </pitch>
    <duration>85</duration>
    <instrument id="P1-I1" />
    <voice>1</voice>
    <type>eighth</type>
    <time-modification>
     <actual-notes>3</actual-notes>
     <normal-notes>2</normal-notes>
     <normal-type>eighth</normal-type>
    </time-modification>
    <stem>up</stem>
    <staff>1</staff>
    <beam number="1">continue</beam>
   </note>
   <note color="#000000" default-x="274" default-y="12">
    <pitch>
     <step>G</step>
     <octave>4</octave>
    </pitch>
    <duration>86</duration>
    <instrument id="P1-I1" />
    <voice>1</voice>
    <type>eighth</type>
    <time-modification>
     <actual-notes>3</actual-notes>
     <normal-notes>2</normal-notes>
     <normal-type>eighth</normal-type>
    </time-modification>
    <stem>up</stem>
    <staff>1</staff>
    <beam number="1">end</beam>
    <notations>
     <tuplet type="stop" bracket="no" number="1" default-y="-20" placement="above" />
    </notations>
   </note>
  </measure>
  
  <measure number="2" width="241">
   <note color="#000000" default-x="15" default-y="-10">
    <pitch>
     <step>D</step>
     <octave>4</octave>
    </pitch>
    <duration>384</duration>
    <instrument id="P1-I1" />
    <voice>1</voice>
    <type>quarter</type>
    <dot />
    <stem>up</stem>
    <staff>1</staff>
   </note>
   <note color="#000000" default-x="101" default-y="-5">
    <pitch>
     <step>E</step>
     <octave>4</octave>
    </pitch>
    <duration>128</duration>
    <instrument id="P1-I1" />
    <voice>1</voice>
    <type>eighth</type>
    <stem>up</stem>
    <staff>1</staff>
   </note>
   <note color="#000000" default-x="148">
    <pitch>
     <step>E</step>
     <alter>1</alter>
     <octave>4</octave>
    </pitch>
    <duration>128</duration>
    <instrument id="P1-I1" />
    <voice>1</voice>
    <type>eighth</type>
    <accidental>sharp</accidental>
    <stem>up</stem>
    <staff>1</staff>
    <beam number="1">begin</beam>
   </note>
   <note color="#000000" default-x="195">
    <pitch>
     <step>F</step>
     <alter>1</alter>
     <octave>4</octave>
    </pitch>
    <duration>128</duration>
    <instrument id="P1-I1" />
    <voice>1</voice>
    <type>eighth</type>
    <stem>up</stem>
    <staff>1</staff>
    <beam number="1">end</beam>
   </note>
  </measure>
  
  <measure number="3" width="290">
   <note color="#000000" default-x="15" default-y="9">
    <pitch>
     <step>G</step>
     <octave>4</octave>
    </pitch>
    <duration>128</duration>
    <instrument id="P1-I1" />
    <voice>1</voice>
    <type>eighth</type>
    <stem>up</stem>
    <staff>1</staff>
    <beam number="1">begin</beam>
   </note>
   <note color="#000000" default-x="61" default-y="9">
    <pitch>
     <step>B</step>
     <octave>4</octave>
    </pitch>
    <duration>128</duration>
    <instrument id="P1-I1" />
    <voice>1</voice>
    <type>eighth</type>
    <stem>up</stem>
    <staff>1</staff>
    <beam number="1">end</beam>
   </note>
   <note color="#000000" default-x="108" default-y="-35">
    <pitch>
     <step>F</step>
     <alter>1</alter>
     <octave>5</octave>
    </pitch>
    <duration>384</duration>
    <instrument id="P1-I1" />
    <voice>1</voice>
    <type>quarter</type>
    <dot />
    <stem>down</stem>
    <staff>1</staff>
   </note>
   <note color="#000000" default-x="195" default-y="-39">
    <pitch>
     <step>E</step>
     <octave>5</octave>
    </pitch>
    <duration>42</duration>
    <instrument id="P1-I1" />
    <voice>1</voice>
    <type>16th</type>
    <accidental>natural</accidental>
    <time-modification>
     <actual-notes>3</actual-notes>
     <normal-notes>2</normal-notes>
     <normal-type>16th</normal-type>
    </time-modification>
    <stem>down</stem>
    <staff>1</staff>
    <beam number="1">begin</beam>
    <beam number="2">begin</beam>
    <notations>
     <tuplet type="start" bracket="no" number="1" default-y="-20" placement="below" />
    </notations>
   </note>
   <note color="#000000" default-x="226" default-y="-39">
    <pitch>
     <step>F</step>
     <alter>1</alter>
     <octave>5</octave>
    </pitch>
    <duration>43</duration>
    <instrument id="P1-I1" />
    <voice>1</voice>
    <type>16th</type>
    <time-modification>
     <actual-notes>3</actual-notes>
     <normal-notes>2</normal-notes>
     <normal-type>16th</normal-type>
    </time-modification>
    <stem>down</stem>
    <staff>1</staff>
    <beam number="1">continue</beam>
    <beam number="2">continue</beam>
   </note>
   <note color="#000000" default-x="258" default-y="-39">
    <pitch>
     <step>E</step>
     <octave>5</octave>
    </pitch>
    <duration>43</duration>
    <instrument id="P1-I1" />
    <voice>1</voice>
    <type>16th</type>
    <time-modification>
     <actual-notes>3</actual-notes>
     <normal-notes>2</normal-notes>
     <normal-type>16th</normal-type>
    </time-modification>
    <stem>down</stem>
    <staff>1</staff>
    <beam number="1">end</beam>
    <beam number="2">end</beam>
    <notations>
     <tuplet type="stop" bracket="no" number="1" default-y="-20" placement="below" />
    </notations>
   </note>
  </measure>
  
  <measure number="4" width="188">
   <note color="#000000" default-x="15" default-y="-45">
    <pitch>
     <step>D</step>
     <octave>5</octave>
    </pitch>
    <duration>512</duration>
    <instrument id="P1-I1" />
    <voice>1</voice>
    <type>half</type>
    <stem>down</stem>
    <staff>1</staff>
   </note>
   <note default-x="124">
    <rest />
    <duration>256</duration>
    <instrument id="P1-I1" />
    <voice>1</voice>
    <type>quarter</type>
    <staff>1</staff>
   </note>
  </measure>
  
  <measure number="5" width="342">
   <print new-system="yes">
    <system-layout>
     <system-margins>
      <left-margin>22</left-margin>
      <right-margin>0</right-margin>
     </system-margins>
     <system-distance>92</system-distance>
    </system-layout>
   </print>
   <attributes>
    <staff-details number="1" print-object="yes" />
   </attributes>
   <note color="#000000" default-x="70" default-y="-50">
    <pitch>
     <step>C</step>
     <octave>5</octave>
    </pitch>
    <duration>256</duration>
    <tie type="start" />
    <instrument id="P1-I1" />
    <voice>1</voice>
    <type>quarter</type>
    <stem>down</stem>
    <staff>1</staff>
    <notations>
     <tied type="start" />
    </notations>
   </note>
   <note color="#000000" default-x="134" default-y="-54">
    <pitch>
     <step>C</step>
     <octave>5</octave>
    </pitch>
    <duration>64</duration>
    <tie type="stop" />
    <instrument id="P1-I1" />
    <voice>1</voice>
    <type>16th</type>
    <stem>down</stem>
    <staff>1</staff>
    <beam number="1">begin</beam>
    <beam number="2">begin</beam>
    <notations>
     <tied type="stop" />
    </notations>
   </note>
   <note color="#000000" default-x="170" default-y="-54">
    <pitch>
     <step>A</step>
     <octave>4</octave>
    </pitch>
    <duration>64</duration>
    <instrument id="P1-I1" />
    <voice>1</voice>
    <type>16th</type>
    <stem>down</stem>
    <staff>1</staff>
    <beam number="1">continue</beam>
    <beam number="2">continue</beam>
   </note>
   <note color="#000000" default-x="206" default-y="-54">
    <pitch>
     <step>C</step>
     <octave>5</octave>
    </pitch>
    <duration>64</duration>
    <instrument id="P1-I1" />
    <voice>1</voice>
    <type>16th</type>
    <stem>down</stem>
    <staff>1</staff>
    <beam number="1">continue</beam>
    <beam number="2">continue</beam>
   </note>
   <note color="#000000" default-x="242" default-y="-54">
    <pitch>
     <step>A</step>
     <octave>4</octave>
    </pitch>
    <duration>64</duration>
    <instrument id="P1-I1" />
    <voice>1</voice>
    <type>16th</type>
    <stem>down</stem>
    <staff>1</staff>
    <beam number="1">end</beam>
    <beam number="2">end</beam>
   </note>
   <note color="#000000" default-x="278">
    <pitch>
     <step>F</step>
     <alter>1</alter>
     <octave>4</octave>
    </pitch>
    <duration>256</duration>
    <instrument id="P1-I1" />
    <voice>1</voice>
    <type>quarter</type>
    <stem>up</stem>
    <staff>1</staff>
   </note>
  </measure>
  
  <measure number="6" width="290">
   <note color="#000000" default-x="15" default-y="-55">
    <pitch>
     <step>B</step>
     <octave>4</octave>
    </pitch>
    <duration>384</duration>
    <instrument id="P1-I1" />
    <voice>1</voice>
    <type>quarter</type>
    <dot />
    <stem>down</stem>
    <staff>1</staff>
   </note>
   <note color="#000000" default-x="102" default-y="12">
    <pitch>
     <step>G</step>
     <octave>4</octave>
    </pitch>
    <duration>42</duration>
    <instrument id="P1-I1" />
    <voice>1</voice>
    <type>16th</type>
    <time-modification>
     <actual-notes>3</actual-notes>
     <normal-notes>2</normal-notes>
     <normal-type>16th</normal-type>
    </time-modification>
    <stem>up</stem>
    <staff>1</staff>
    <beam number="1">begin</beam>
    <beam number="2">begin</beam>
    <notations>
     <tuplet type="start" bracket="no" number="1" default-y="-20" placement="above" />
    </notations>
   </note>
   <note color="#000000" default-x="134" default-y="12">
    <pitch>
     <step>B</step>
     <octave>4</octave>
    </pitch>
    <duration>43</duration>
    <instrument id="P1-I1" />
    <voice>1</voice>
    <type>16th</type>
    <time-modification>
     <actual-notes>3</actual-notes>
     <normal-notes>2</normal-notes>
     <normal-type>16th</normal-type>
    </time-modification>
    <stem>up</stem>
    <staff>1</staff>
    <beam number="1">continue</beam>
    <beam number="2">continue</beam>
   </note>
   <note color="#000000" default-x="165" default-y="12">
    <pitch>
     <step>G</step>
     <octave>4</octave>
    </pitch>
    <duration>43</duration>
    <instrument id="P1-I1" />
    <voice>1</voice>
    <type>16th</type>
    <time-modification>
     <actual-notes>3</actual-notes>
     <normal-notes>2</normal-notes>
     <normal-type>16th</normal-type>
    </time-modification>
    <stem>up</stem>
    <staff>1</staff>
    <beam number="1">end</beam>
    <beam number="2">end</beam>
    <notations>
     <tuplet type="stop" bracket="no" number="1" default-y="-20" placement="above" />
    </notations>
   </note>
   <note color="#000000" default-x="197" default-y="-10">
    <pitch>
     <step>D</step>
     <octave>4</octave>
    </pitch>
    <duration>128</duration>
    <instrument id="P1-I1" />
    <voice>1</voice>
    <type>eighth</type>
    <stem>up</stem>
    <staff>1</staff>
    <beam number="1">begin</beam>
   </note>
   <note color="#000000" default-x="244" default-y="-10">
    <pitch>
     <step>D</step>
     <alter>1</alter>
     <octave>4</octave>
    </pitch>
    <duration>128</duration>
    <instrument id="P1-I1" />
    <voice>1</voice>
    <type>eighth</type>
    <accidental>sharp</accidental>
    <stem>up</stem>
    <staff>1</staff>
    <beam number="1">end</beam>
   </note>
  </measure>
  
  <measure number="7" width="238">
   <note color="#000000" default-x="15" default-y="-5">
    <pitch>
     <step>E</step>
     <octave>4</octave>
    </pitch>
    <duration>128</duration>
    <instrument id="P1-I1" />
    <voice>1</voice>
    <type>eighth</type>
    <stem>up</stem>
    <staff>1</staff>
   </note>
   <note color="#000000" default-x="61" default-y="-50">
    <pitch>
     <step>C</step>
     <octave>5</octave>
    </pitch>
    <duration>256</duration>
    <instrument id="P1-I1" />
    <voice>1</voice>
    <type>quarter</type>
    <stem>down</stem>
    <staff>1</staff>
   </note>
   <note color="#000000" default-x="126" default-y="10">
    <pitch>
     <step>A</step>
     <octave>4</octave>
    </pitch>
    <duration>256</duration>
    <instrument id="P1-I1" />
    <voice>1</voice>
    <type>quarter</type>
    <stem>up</stem>
    <staff>1</staff>
   </note>
   <note color="#000000" default-x="191">
    <pitch>
     <step>F</step>
     <alter>1</alter>
     <octave>4</octave>
    </pitch>
    <duration>128</duration>
    <instrument id="P1-I1" />
    <voice>1</voice>
    <type>eighth</type>
    <stem>up</stem>
    <staff>1</staff>
   </note>
  </measure>
  
  <measure number="8" width="160">
   <note color="#000000" default-x="15" default-y="5">
    <pitch>
     <step>G</step>
     <octave>4</octave>
    </pitch>
    <duration>768</duration>
    <instrument id="P1-I1" />
    <voice>1</voice>
    <type>half</type>
    <dot />
    <stem>up</stem>
    <staff>1</staff>
   </note>
   <barline>
    <bar-style>light-heavy</bar-style>
   </barline>
  </measure>
 </part>
</score-partwise>

**Comment by Danielku15** [comment] 2017-03-28 04:59
Sorry, but this is not how bugreports work. I will not just remove some because of a screenshot. I want to be able to reproduce the problem on my side and then add a proper fix for it. Just removing some code might open up 10 other problems.

**Comment by gburlet** [comment] 2017-03-28 06:33
@Danielku15 Let me save you some time. Below is his MusicXML file (compressed). I'm not sure why @LYH8112 won't just give you the MusicXML file.

[LYH8112_bug.zip](https://github.com/CoderLine/alphaTab/files/874654/LYH8112_bug.zip)

**Comment by LYH8112** [comment] 2017-03-28 09:11
The rest is incorrect. Please check the musicxml file.
[Rest.xlsx](https://github.com/CoderLine/alphaTab/files/875076/Rest.xlsx)

**Comment by Danielku15** [comment] 2017-03-28 11:14
Just out of curiosity: Are you writing the MusicXMLs on your own? Which Software are you using? MusicXML seems to come in many different flavours.

**Comment by LYH8112** [comment] 2017-03-28 13:41
@Danielku15  MuseScore

**Comment by Danielku15** [comment] 2017-06-05 18:07
There was an issue on the handling of empty voices/beats which should be fixed now. The two testfiles worked for me.

**Closed by Danielku15** 2017-06-05 18:07 UTC
Labels: More Info Required
