### ISSUE TITLE
Metronome can't be switched off

### ISSUE THREAD

**Issue by nascent** [CoderLine/alphaTab#209] opened 2018-11-09 07:01 UTC
# Your environment

JavaScript Developer library

# Expected Results

Metronome switched off during playback after being switched on

# Observed Results

Metronome cannot be switched off arbitrarily

# Steps to Reproduce (for bugs)

1. Press play
2. Switch metronome on
3. Attempt to switch metronome off

# Possible Solution 

None found

**Comment by Danielku15** [comment] 2018-11-11 16:14
Looks like something broke lately on the samples to enable/disable the metronome.

**Comment by Danielku15** [comment] 2018-11-17 18:56
The problem is fixed with the latest changes. There were some wrong checks on whether to only read or only set the metronome value (and others).

**Closed by Danielku15** 2018-11-17 18:56 UTC
Labels: :spider:  bug, accepted, documentation, platform-javascript
