### ISSUE TITLE
Alphatex fails to render with chord names and diagrams

### ISSUE THREAD

**Issue by chris-saunders** [CoderLine/alphaTab#224] opened 2019-01-17 22:57 UTC
# Your environment

* Version used: Dev branch
* Platform used: JavaScript
* Rendering engine used: SVG
* Browser Name and Version: Chrome, Firefox, Opera
* Operating System and version: Desktop (MacOS Mojave 10.14)
* Link to your project:

# Expected Results
Alphatab renders the sheet music, chord diagrams names and all.

# Observed Results
Alphatab JS crashes before rendering.
`AlphaTab.js:2642 Uncaught TypeError: Cannot read property 'cmd' of null
    at AlphaTab.js:2642`
Seems that $global.data is null, which prevents rendering and when the render message is logged it crashes because there is no information associated with it.

# Steps to Reproduce (for bugs)
Here is the alphatex which causes the bug.
Important to note, alphatab renders fine on other pieces of sheet music with chord names and diagrams, and it also works fine if you remove all chord names and diagrams from the piece linked below. Another way to get the piece to render is to remove a fairly large amount of bars while leaving the chord information in.

It also renders on Safari with no issues. Have not tested with IE or Edge.

[bohemianRhapsody.txt](https://github.com/CoderLine/alphaTab/files/2770896/bohemianRhapsody.txt)

# Possible Solution 
It seems to be an issue related to size of the file and rendering chord names and diagrams.

**Comment by Danielku15** [comment] 2019-01-20 18:07
The problem is fixed with the latest changes in the develop branch. There was a cycic reference when the song was serialized. With my changes your song is working fine.

**Closed by Danielku15** 2019-01-20 18:07 UTC
Labels: :spider:  bug, accepted, file-format-alphaTex, file-formats, platform-javascript
