### ISSUE TITLE
Notes above g5 render incorrectly

### ISSUE THREAD

**Issue by weltkante** [CoderLine/alphaTab#184] opened 2018-05-26 16:19 UTC
# Your environment

* Version used: master branch
* Platform used: C# (WPF)
* Rendering engine: GDI
* Operating System: Windows 10 / 1803

# Expected Results

Notes above g5 alternating dashed and non-dashed, for example as displayed here: https://jythonmusic.me/ch-2-elements-of-music-and-code/

# Observed Results

Note a5 is not dashed but b5 is, and from there on the alternation is off by one to other applications. (Also the dash is only visible on the left so its not very readable, most visualizations extend the stroke through the note on both sides.)

![grafik](https://user-images.githubusercontent.com/5845814/40578187-135ab84c-6110-11e8-8dea-2a7cf50c8639.png)

# Steps to Reproduce (for bugs)

`\tuning piano . f5 g5 a5 b5 | c6 d6 e6 f6`

**Comment by Danielku15** [comment] 2018-05-28 08:01
Thanks for highlighting this issue. The problem is already fixed locally, I will soon push a new version of alphaTab to GitHub with a bunch of enhancements and bugfixes.

**Comment by Danielku15** [comment] 2018-07-28 16:03
This problem should be fixed with the new version on the `develop` branch.

**Closed by Danielku15** 2018-07-28 16:03 UTC
Labels: :spider:  bug, accepted, rendering
