### ISSUE TITLE
Horizontal tab layout overlaped by vertical tab layout

### ISSUE THREAD

**Issue by WindBise** [CoderLine/alphaTab#1114] opened 2023-02-11 05:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In horizontal layout mode, the sheet is overlapped

### Expected Behavior

When switch to horizontal layout, the layout should only be horizontal, without vertial layout overlap on it.

### Steps To Reproduce

1. open https://alphatab.net/
2. load the gp file in zip
[River Flows In You.gp.zip](https://github.com/CoderLine/alphaTab/files/10712651/River.Flows.In.You.gp.zip)
3. switch to Horizontal Layout (Off-Screen)
4. then the layout appears to be overlapped

### Found in Version

1.2

### Platform

Web

### Environment

```markdown
- **OS**: mac os
- **Browser**: chrome
- **.net Version**:
```

**Comment by Danielku15** [comment] 2023-02-11 09:19
Duplicate of https://github.com/CoderLine/alphaTab/issues/1090
Fixed in 1.3 https://github.com/CoderLine/alphaTab/pull/1091

**Closed by Danielku15** 2023-02-11 09:19 UTC
Labels: :spider: type-bug, state-duplicate
